version: "{build}"

skip_tags: true
clone_folder: C:\CI\bolt

platform:
 - x86
 - x64

configuration:
 - Release
 - Release+Debug
 - Debug

environment:
  EXCHANGE_TEST_PASSWORD: password_in_yml_file
  matrix:
  - NODE_VERSION: 4.2.4

install:
  - echo "EXCHANGE_TEST_PASSWORD %EXCHANGE_TEST_PASSWORD%"
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  - cd /d %APPVEYOR_BUILD_FOLDER%
  - python build\install.py

build_script:
  - cd /d %APPVEYOR_BUILD_FOLDER%
  - python build\build.py "--arch=%PLATFORM%" "--variant=%CONFIGURATION%" "--target=xulrunner"

test: off
deploy: off

artifacts:
  - path: atom-build

cache:
  - mozbuild.zip -> build-config.json
  - mozilla-build.zip -> build-config.json
  - comm.zip -> build-config.json
  - comm-mozilla.zip -> build-config.json
  - node_modules
  - '%USERPROFILE%\.atom\.apm'
  - '%USERPROFILE%\.atom\.node-gyp\.atom'
  - '%USERPROFILE%\.atom\.npm'