version: "{build}"

skip_tags: true
clone_folder: C:\CI\bolt

platform:
  - x86
#  - x64

configuration:
#  - Debug
  - Release
#  - Release+Debug

environment:
  matrix:
  - NODE_VERSION: 4.2.4

install:
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  - cd /d %APPVEYOR_BUILD_FOLDER%
  - python build\install.py

build_script:
  - cd /d %APPVEYOR_BUILD_FOLDER%
  - CI-Build.cmd

test: off
deploy: off

artifacts:
  - path: atom-build

cache:
  - mozbuild
  - mozilla-build
  - comm
  - node_modules
  - '%USERPROFILE%\.atom\.apm'
  - '%USERPROFILE%\.atom\.node-gyp\.atom'
  - '%USERPROFILE%\.atom\.npm'