version: "{build}"

skip_tags: true
clone_folder: C:\CI\bolt
clone_depth: 10

platform:
  - x86

environment:
  matrix:
  - NODE_VERSION: 0.10.35

install:
  - SET PATH=C:\Program Files\Atom\resources\cli;%PATH%
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\CI\bolt\script\cibuild.cmd

test: off
deploy: off
artifacts:
  - path: atom-build

cache:
  - '%USERPROFILE%\.atom\.apm'
  - '%USERPROFILE%\.atom\.node-gyp\.atom'
  - '%USERPROFILE%\.atom\.npm'